#!/bin/bash
tail -n 1 iacta | cat >> iacta#!/bin/bash
tail -n 1 iacta | cat >> iacta#!/bin/bash
tail -n 1 iacta | cat >> iacta#!/bin/bash
tail -n 1 iacta | cat >> iacta#!/bin/bash
tail -n 1 iacta | cat >> iacta#!/bin/bash
tail -n 1 iacta | cat >> iacta#!/bin/bash
tail -n 1 iacta | cat >> iacta#!/bin/bash
tail -n 1 iacta | cat >> iacta#!/bin/bash
tail -n 1 iacta | cat >> iacta
